/**
 * AI Content Analysis Engine
 * Uses Google Gemini AI (free tier) for real analysis
 * Falls back to heuristic simulation when API key is not configured
 */

import {
  isGeminiConfigured,
  analyzeTextWithGemini as callGeminiText,
  analyzeImageWithGemini as callGeminiImage,
  analyzeImageBase64WithGemini as callGeminiImageBase64,
  analyzeVideoWithGemini as callGeminiVideo,
  analyzeVideoFramesWithGemini as callGeminiVideoFrames
} from '../config/gemini'

// ============================================================
// SCAN STATUS MESSAGES
// ============================================================

const SCAN_MESSAGES = {
  text: [
    'Analyzing linguistic patterns…',
    'Checking syntactic consistency…',
    'Evaluating vocabulary distribution…',
    'Detecting repetitive phrasing…',
    'Scanning for AI writing markers…',
    'Analyzing sentence structure…',
    'Computing perplexity scores…',
    'Generating analysis report…'
  ],
  image: [
    'Analyzing pixel patterns…',
    'Checking for synthetic artifacts…',
    'Scanning metadata signatures…',
    'Evaluating color consistency…',
    'Detecting manipulation indicators…',
    'Analyzing noise patterns…',
    'Computing authenticity score…',
    'Generating analysis report…'
  ],
  video: [
    'Extracting key frames…',
    'Analyzing facial landmarks…',
    'Checking temporal consistency…',
    'Scanning for deepfake artifacts…',
    'Evaluating motion patterns…',
    'Analyzing audio-visual sync…',
    'Computing deepfake probability…',
    'Generating analysis report…'
  ],
  url: [
    'Fetching content from URL…',
    'Detecting content type…',
    'Downloading media content…',
    'Running visual analysis…',
    'Analyzing content patterns…',
    'Detecting synthetic generation…',
    'Computing analysis scores…',
    'Generating analysis report…'
  ]
}

// ============================================================
// GEMINI AI PROMPTS
// ============================================================

const TEXT_ANALYSIS_PROMPT = `You are an expert AI content detection system. Analyze the following text and determine whether it was written by a human or generated by AI (like ChatGPT, Claude, Gemini, etc.).

Evaluate these factors:
- Writing style consistency and naturalness
- Vocabulary diversity and word choice patterns
- Sentence structure variation
- Repetitive phrasing or formulaic patterns
- Burstiness (variation in sentence length/complexity — humans are more bursty)
- Perplexity (predictability of word choices — AI tends to be more predictable)
- Use of hedging language, filler phrases, or overly polished transitions
- Emotional authenticity and personal voice

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": <number 0-100>,
  "humanProbability": <number 0-100>,
  "confidence": <number 0-100>,
  "summary": "<2-3 sentence summary of findings>",
  "patterns": [
    {"type": "warning|success|info", "text": "<pattern description>"}
  ],
  "explanation": "<detailed 3-4 sentence explanation of why you reached this conclusion>",
  "metrics": {
    "writingStyle": "<natural|formulaic|mixed>",
    "burstiness": "<low|medium|high>",
    "predictability": "<low|medium|high>",
    "emotionalDepth": "<shallow|moderate|deep>"
  }
}

Text to analyze:
"""
{TEXT}
"""`

const IMAGE_ANALYSIS_PROMPT = `You are an expert AI image forensics analyst specializing in detecting MODERN AI-generated images. Today's AI generators (Midjourney v6, DALL-E 3, Stable Diffusion XL, Gemini Imagen, Flux) produce extremely high-quality, near-perfect images. You MUST NOT assume an image is human-made just because it looks clean or professional.

IMPORTANT: Modern AI-generated images are often FLAWLESS — perfect text, perfect lighting, perfect composition. "Too perfect" IS an indicator of AI generation, not a sign of human creation.

Evaluate ALL of the following carefully:

**Classic AI artifacts (older generators):**
- Distorted hands, fingers, teeth, or small details
- Garbled or inconsistent text
- Unusual blending around edges
- Background inconsistencies

**Modern AI indicators (CRITICAL — these are the most common today):**
- Unnaturally smooth or plastic-looking textures and surfaces
- Hyper-realistic rendering that looks "too clean" or "too perfect"
- Suspiciously perfect symmetry, alignment, or composition
- A "stock photo" or "render" quality — generic and flawless
- Uniform lighting that is TOO consistent (no natural imperfections)
- Colors that are TOO vibrant, saturated, or harmoniously balanced
- Details that are impressive at first glance but lack depth on closer inspection
- Flat or generic facial expressions, poses, or backgrounds
- An overall "uncanny" feel — technically perfect but emotionally hollow
- Infographic or illustration style that looks templated or algorithmically generated
- A style strongly resembling known AI generators (Midjourney's painterly look, DALL-E's clean renders, Gemini's photorealistic style)

**Metadata and context clues:**
- The filename may contain generator names (e.g., "Midjourney", "DALL-E", "Gemini_Generated", "ComfyUI", "SD", "flux")
- Round or standardized resolutions (1024x1024, 1792x1024, etc.)
- Lack of camera EXIF data patterns

**Signs of HUMAN creation:**
- Natural imperfections: slight blur, noise, lens distortion, motion blur
- Real camera artifacts: bokeh, chromatic aberration, lens flare
- Authentic human elements: genuine emotion, real environment context
- Signs of physical media: brush strokes, paper texture, pen marks
- Real-world context clues: timestamps, recognizable locations, natural wear

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": <number 0-100>,
  "humanProbability": <number 0-100>,
  "confidence": <number 0-100>,
  "summary": "<2-3 sentence summary of findings>",
  "patterns": [
    {"type": "warning|success|info", "text": "<observation>"}
  ],
  "explanation": "<detailed 3-4 sentence explanation>",
  "metrics": {
    "textureConsistency": "<normal|suspicious|anomalous>",
    "lightingAnalysis": "<consistent|inconsistent>",
    "detailAccuracy": "<accurate|distorted|mixed>",
    "overallAuthenticity": "<authentic|synthetic|uncertain>"
  }
}`

const VIDEO_ANALYSIS_PROMPT = `You are an expert deepfake forensics analyst. Your job is to accurately distinguish between REAL video footage and AI-generated/deepfake video. You must be precise — both false negatives (missing deepfakes) AND false positives (flagging real video as fake) are serious errors.

You are being shown multiple frames extracted from the video. Compare them carefully.

IMPORTANT CONTEXT — DO NOT over-flag these as deepfakes:
- Real people often wear makeup, foundation, or have professionally groomed skin — this is NOT a deepfake indicator
- Professional/HD cameras and good studio lighting naturally make skin look smoother — this is NOT a deepfake indicator  
- Celebrities, athletes, and public figures often look very polished in real life — this is NOT a deepfake indicator
- Video compression (especially screen recordings or social media) reduces skin texture detail — this is NOT a deepfake indicator
- A crowded, chaotic, real-world environment (stadiums, events, streets) with natural camera shake strongly suggests REAL footage

**ACTUAL DEEPFAKE ARTIFACTS (focus on THESE — they are the real technical tells):**

Face-Swap Technical Artifacts:
- Visible blending boundary or color mismatch where face meets hair, ears, or neck (a hard edge or halo effect)
- Face that appears "pasted on" — different resolution, sharpness, or noise level than the rest of the body/scene
- Ears that are blurry, distorted, or missing detail while the face is sharp
- Teeth that morph, blur, or change shape between frames
- Eyes with mismatched or missing reflections (left eye reflection doesn't match right)
- Warping or distortion in the background near face edges (background bends around the face)

Temporal Artifacts (THE STRONGEST TELLS — compare across frames):
- Face shape or proportions that CLEARLY shift between frames (jaw widens/narrows, face stretches)
- Skin texture that is dramatically different between frames (not just lighting changes)
- Flickering, shimmering, or "swimming" effect around face edges between frames
- Face lighting that changes independently from the environment lighting
- Moments where the face briefly glitches, distorts, or shows artifacts

Fully AI-Generated Video Tells:
- Scene looks entirely synthetic — no real camera artifacts at all
- Physics-defying elements (impossible reflections, objects clipping through each other)
- Everyone in the scene has the same smooth, synthetic quality
- Background lacks real-world detail and complexity

**STRONG SIGNS OF GENUINE/REAL VIDEO (give these proper weight):**
- Natural, complex, real-world environment with real objects, people, and depth
- Multiple real people in the scene interacting naturally
- Natural camera motion: handheld shake, auto-focus adjustments, exposure changes
- Real camera artifacts: motion blur, lens flare, chromatic aberration, rolling shutter
- Genuine environmental details: real signage, complex backgrounds, natural shadows from multiple light sources
- Skin that is smooth but still has SOME visible texture, pores, or natural blemishes
- Natural body proportions and movements that are fluid and physically correct
- Clothing that folds, wrinkles, and moves naturally with the body

DECISION GUIDELINES:
- If the environment is clearly real and complex (stadium, street, event) and people are interacting naturally → lean toward AUTHENTIC unless you see clear technical artifacts
- If skin is smooth but the rest of the scene is rich with real-world detail → it's likely makeup/camera/lighting, NOT deepfake
- Only flag as deepfake if you see ACTUAL technical artifacts (boundary issues, temporal glitches, face-body mismatch), not just "smooth skin"
- A confidence below 60% means you're unsure — use it honestly when the evidence is ambiguous

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": <number 0-100>,
  "humanProbability": <number 0-100>,
  "confidence": <number 0-100>,
  "summary": "<2-3 sentence summary of findings>",
  "patterns": [
    {"type": "warning|success|info", "text": "<observation>"}
  ],
  "explanation": "<detailed 3-4 sentence explanation>",
  "metrics": {
    "facialConsistency": "<natural|suspicious|anomalous>",
    "temporalCoherence": "<stable|unstable|mixed>",
    "lipSyncAccuracy": "<accurate|inaccurate|not_applicable>",
    "overallAuthenticity": "<authentic|deepfake|uncertain>"
  }
}`

// ============================================================
// URL CONTENT DETECTION HELPERS
// ============================================================

/**
 * Detect what type of content a URL likely points to
 */
function detectURLContentType(url) {
  const u = url.toLowerCase()

  // Direct image URLs
  if (/\.(jpg|jpeg|png|gif|webp|bmp|svg|avif|tiff)(\?.*)?$/i.test(u)) return 'image'

  // Direct video URLs
  if (/\.(mp4|webm|mov|avi|mkv|m4v)(\?.*)?$/i.test(u)) return 'video'

  // Known image hosting platforms
  const imageHosts = [
    'imgur.com', 'i.imgur.com', 'i.redd.it', 'preview.redd.it',
    'pbs.twimg.com', 'images.unsplash.com',
    'th.bing.com', 'googleusercontent.com',
    'flickr.com', 'staticflickr.com',
    'pinimg.com', 'cdninstagram.com', 'scontent',
    'fbcdn.net'
  ]
  if (imageHosts.some(h => u.includes(h))) return 'image'

  // Instagram posts (contain images/videos)
  if (u.includes('instagram.com/p/') || u.includes('instagram.com/reel/')) return 'instagram'

  // Video platforms
  if (u.includes('youtube.com/watch') || u.includes('youtu.be/')) return 'youtube'
  if (u.includes('tiktok.com')) return 'tiktok'
  if (u.includes('vimeo.com')) return 'vimeo'
  if (u.includes('twitter.com') || u.includes('x.com')) return 'social'
  if (u.includes('facebook.com') || u.includes('fb.com')) return 'social'

  return 'webpage'
}

/**
 * Try to fetch a URL as an image and return base64
 */
async function fetchImageFromURL(url) {
  try {
    // Use a CORS proxy for cross-origin requests
    const proxies = [
      url, // Try direct first
      `https://corsproxy.io/?${encodeURIComponent(url)}`,
      `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
    ]

    for (const proxyUrl of proxies) {
      try {
        const response = await fetch(proxyUrl, {
          headers: { 'Accept': 'image/*,*/*' },
          signal: AbortSignal.timeout(10000)
        })

        if (!response.ok) continue

        const contentType = response.headers.get('content-type') || ''

        // Check if response is actually an image
        if (contentType.startsWith('image/') || contentType === 'application/octet-stream') {
          const blob = await response.blob()
          if (blob.size < 100) continue // Too small, probably an error page

          const mimeType = contentType.startsWith('image/') ? contentType.split(';')[0] : 'image/jpeg'
          const base64 = await blobToBase64(blob)

          console.log(`[Veritas AI] ✓ Fetched image from URL (${(blob.size / 1024).toFixed(1)} KB)`)
          return { base64, mimeType, size: blob.size }
        }
      } catch (e) {
        continue
      }
    }

    return null
  } catch (err) {
    console.warn('[Veritas AI] Failed to fetch image from URL:', err.message)
    return null
  }
}

/**
 * Try to get a thumbnail/preview image for video platform URLs
 */
function getVideoThumbnailURL(url) {
  const u = url.toLowerCase()

  // YouTube
  if (u.includes('youtube.com/watch') || u.includes('youtu.be/')) {
    let videoId = null
    if (u.includes('youtube.com/watch')) {
      const params = new URL(url).searchParams
      videoId = params.get('v')
    } else if (u.includes('youtu.be/')) {
      videoId = url.split('youtu.be/')[1]?.split(/[?&#]/)[0]
    }
    if (videoId) {
      // YouTube provides direct thumbnail access — try maxresdefault, then hqdefault
      return [
        `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
        `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
        `https://img.youtube.com/vi/${videoId}/0.jpg`,
      ]
    }
  }

  // Vimeo (requires API call, use generic approach)
  if (u.includes('vimeo.com')) {
    const vimeoId = url.split('vimeo.com/')[1]?.split(/[?&#/]/)[0]
    if (vimeoId) {
      return [`https://vumbnail.com/${vimeoId}.jpg`]
    }
  }

  return null
}

/**
 * Fetch image from social media platforms using metadata extraction APIs
 * These APIs render the page with a headless browser, so they work with
 * JavaScript-rendered pages like Instagram, TikTok, Twitter, etc.
 */
async function fetchImageFromPlatform(url) {
  const services = [
    // Microlink — renders the page and extracts metadata
    async () => {
      const apiUrl = `https://api.microlink.io/?url=${encodeURIComponent(url)}`
      const res = await fetch(apiUrl, { signal: AbortSignal.timeout(15000) })
      if (!res.ok) return null
      const data = await res.json()
      const imgUrl = data?.data?.image?.url || data?.data?.screenshot?.url
      if (imgUrl) {
        console.log('[Veritas AI] ✓ Got image via Microlink:', imgUrl.slice(0, 80))
        return imgUrl
      }
      return null
    },
    // jsonlink.io — another metadata extraction service
    async () => {
      const apiUrl = `https://jsonlink.io/api/extract?url=${encodeURIComponent(url)}`
      const res = await fetch(apiUrl, { signal: AbortSignal.timeout(12000) })
      if (!res.ok) return null
      const data = await res.json()
      const imgs = data?.images
      if (imgs && imgs.length > 0) {
        console.log('[Veritas AI] ✓ Got image via jsonlink.io:', imgs[0].slice(0, 80))
        return imgs[0]
      }
      return null
    },
    // Open Graph scraper via noembed (works for some platforms)
    async () => {
      const apiUrl = `https://noembed.com/embed?url=${encodeURIComponent(url)}`
      const res = await fetch(apiUrl, { signal: AbortSignal.timeout(10000) })
      if (!res.ok) return null
      const data = await res.json()
      if (data?.thumbnail_url) {
        console.log('[Veritas AI] ✓ Got image via noembed:', data.thumbnail_url.slice(0, 80))
        return data.thumbnail_url
      }
      return null
    },
  ]

  for (const service of services) {
    try {
      const imageUrl = await service()
      if (imageUrl) return imageUrl
    } catch (e) {
      console.warn('[Veritas AI] Platform image fetch attempt failed:', e.message)
      continue
    }
  }

  return null
}

/**
 * Convert Blob to base64
 */
function blobToBase64(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => resolve(reader.result.split(',')[1])
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

// ============================================================
// GEMINI-POWERED ANALYSIS FUNCTIONS
// ============================================================

async function analyzeTextWithGemini(text) {
  if (!isGeminiConfigured()) return null

  try {
    const responseText = await callGeminiText(text, TEXT_ANALYSIS_PROMPT)
    if (!responseText) return null

    // Clean response — remove markdown code fences if present
    const cleaned = responseText.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim()
    const analysis = JSON.parse(cleaned)

    // Compute text metrics locally
    const wordCount = text.split(/\s+/).filter(Boolean).length
    const sentenceCount = text.split(/[.!?]+/).filter(Boolean).length
    const uniqueWords = new Set(text.toLowerCase().split(/\s+/)).size
    const avgWordLength = text.replace(/\s/g, '').length / Math.max(wordCount, 1)
    const lexicalDiversity = uniqueWords / Math.max(wordCount, 1)

    return {
      type: 'text',
      aiProbability: clamp(analysis.aiProbability, 0, 100),
      humanProbability: clamp(analysis.humanProbability, 0, 100),
      confidence: clamp(analysis.confidence, 0, 100),
      summary: analysis.summary,
      patterns: (analysis.patterns || []).map(p => ({
        type: p.type || 'info',
        text: p.text
      })),
      explanation: analysis.explanation,
      metrics: {
        wordCount,
        sentenceCount,
        avgWordLength: Math.round(avgWordLength * 10) / 10,
        lexicalDiversity: Math.round(lexicalDiversity * 100) / 100,
        uniqueWords,
        ...(analysis.metrics || {})
      },
      chartData: generateChartData(analysis.aiProbability),
      poweredBy: 'Gemini AI'
    }
  } catch (error) {
    console.error('Gemini text analysis error:', error?.message || error)
    return null // Fallback to simulation
  }
}

async function analyzeImageWithGemini(imageFile) {
  if (!isGeminiConfigured() || !imageFile) return null

  try {
    // Build the prompt with filename context — filenames can contain strong AI signals
    let prompt = IMAGE_ANALYSIS_PROMPT
    const fileName = imageFile.name || ''
    const fileMeta = []

    if (fileName) fileMeta.push(`Filename: "${fileName}"`)
    if (imageFile.size) fileMeta.push(`File size: ${(imageFile.size / 1024).toFixed(0)} KB`)
    if (imageFile.type) fileMeta.push(`MIME type: ${imageFile.type}`)

    if (fileMeta.length > 0) {
      prompt += `\n\nFile metadata (use as additional context — a filename containing "Gemini_Generated", "Midjourney", "DALL-E", "ComfyUI", "SD_output", "flux", or similar is a VERY strong indicator the image is AI-generated):\n${fileMeta.join('\n')}`
    }

    const responseText = await callGeminiImage(imageFile, prompt)
    if (!responseText) return null

    const cleaned = responseText.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim()
    const analysis = JSON.parse(cleaned)

    return {
      type: 'image',
      aiProbability: clamp(analysis.aiProbability, 0, 100),
      humanProbability: clamp(analysis.humanProbability, 0, 100),
      confidence: clamp(analysis.confidence, 0, 100),
      summary: analysis.summary,
      patterns: (analysis.patterns || []).map(p => ({
        type: p.type || 'info',
        text: p.text
      })),
      explanation: analysis.explanation,
      metrics: {
        fileName: imageFile.name,
        fileSize: `${(imageFile.size / 1024).toFixed(1)} KB`,
        format: imageFile.type?.split('/')[1]?.toUpperCase() || 'UNKNOWN',
        ...(analysis.metrics || {})
      },
      chartData: generateChartData(analysis.aiProbability),
      poweredBy: 'Gemini AI Vision'
    }
  } catch (error) {
    console.error('Gemini image analysis error:', error?.message || error)
    return null
  }
}

async function analyzeVideoWithGemini(videoFile) {
  if (!isGeminiConfigured() || !videoFile) {
    console.warn('[Veritas AI] Video analysis skipped — Gemini not configured or no file')
    return null
  }

  try {
    console.log(`[Veritas AI] Analyzer: starting video analysis for ${videoFile.name}`)
    const responseText = await callGeminiVideo(videoFile, VIDEO_ANALYSIS_PROMPT)

    if (!responseText) {
      console.error('[Veritas AI] Analyzer: Gemini returned no response for video')
      return null
    }

    console.log('[Veritas AI] Analyzer: got Gemini response, parsing...')
    const cleaned = responseText.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim()

    let analysis
    try {
      analysis = JSON.parse(cleaned)
    } catch (parseErr) {
      console.error('[Veritas AI] Analyzer: Failed to parse Gemini video response as JSON:', parseErr.message)
      console.error('[Veritas AI] Raw response:', cleaned.slice(0, 500))
      return null
    }

    console.log(`[Veritas AI] ✓ Video analysis complete: AI=${analysis.aiProbability}%, confidence=${analysis.confidence}%`)

    return {
      type: 'video',
      aiProbability: clamp(analysis.aiProbability, 0, 100),
      humanProbability: clamp(analysis.humanProbability, 0, 100),
      confidence: clamp(analysis.confidence, 0, 100),
      summary: analysis.summary,
      patterns: (analysis.patterns || []).map(p => ({
        type: p.type || 'info',
        text: p.text
      })),
      explanation: analysis.explanation,
      metrics: {
        fileName: videoFile.name,
        fileSize: `${(videoFile.size / (1024 * 1024)).toFixed(1)} MB`,
        format: videoFile.type?.split('/')[1]?.toUpperCase() || 'MP4',
        ...(analysis.metrics || {})
      },
      chartData: generateChartData(analysis.aiProbability),
      poweredBy: 'Gemini AI Vision'
    }
  } catch (error) {
    console.error('[Veritas AI] Gemini video analysis error:', error?.message || error)
    return null
  }
}

async function analyzeURLWithGemini(url) {
  if (!isGeminiConfigured()) return null

  try {
    const contentType = detectURLContentType(url)
    console.log(`[Veritas AI] URL content type detected: ${contentType} for ${url}`)

    let responseText = null
    let analysisType = 'url'
    let sourceDetail = contentType

    // ─── Strategy 1: Direct Image URL — fetch and analyze visually ───
    if (contentType === 'image') {
      console.log('[Veritas AI] Attempting to fetch image from URL for visual analysis...')
      const imageData = await fetchImageFromURL(url)

      if (imageData) {
        responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType, IMAGE_ANALYSIS_PROMPT)
        analysisType = 'image'
        sourceDetail = 'image (fetched from URL)'
      }
    }

    // ─── Strategy 2: Instagram — use metadata APIs that render the page ───
    if (!responseText && contentType === 'instagram') {
      console.log('[Veritas AI] Instagram URL detected — fetching image via platform APIs...')

      // Instagram blocks CORS and og:image scraping — use metadata APIs instead
      const platformImageUrl = await fetchImageFromPlatform(url)
      if (platformImageUrl) {
        const imageData = await fetchImageFromURL(platformImageUrl)
        if (imageData) {
          responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType,
            IMAGE_ANALYSIS_PROMPT + '\n\nNote: This image was extracted from an Instagram post. Analyze the actual visual content of the image for AI generation indicators. Do NOT base your analysis on the platform — focus only on what you see in the image.')
          analysisType = 'image'
          sourceDetail = 'Instagram image'
        }
      }

      // Fallback: try og:image extraction (unlikely to work for Instagram but worth trying)
      if (!responseText) {
        const ogImage = await extractOGImage(url)
        if (ogImage) {
          const imageData = await fetchImageFromURL(ogImage)
          if (imageData) {
            responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType,
              IMAGE_ANALYSIS_PROMPT + '\n\nNote: This image was extracted from an Instagram post. Analyze the actual visual content.')
            analysisType = 'image'
            sourceDetail = 'Instagram image'
          }
        }
      }
    }

    // ─── Strategy 3: Social media (Twitter/X, Facebook) — use platform APIs then og:image ───
    if (!responseText && contentType === 'social') {
      console.log('[Veritas AI] Social media URL — fetching image via platform APIs...')

      // Try metadata APIs first (they render JS pages)
      const platformImageUrl = await fetchImageFromPlatform(url)
      if (platformImageUrl) {
        const imageData = await fetchImageFromURL(platformImageUrl)
        if (imageData) {
          responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType,
            IMAGE_ANALYSIS_PROMPT + '\n\nNote: This image was extracted from a social media post. Analyze the actual visual content for AI generation indicators.')
          analysisType = 'image'
          sourceDetail = 'social media image'
        }
      }

      // Fallback to og:image
      if (!responseText) {
        const ogImage = await extractOGImage(url)
        if (ogImage) {
          const imageData = await fetchImageFromURL(ogImage)
          if (imageData) {
            responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType,
              IMAGE_ANALYSIS_PROMPT + '\n\nNote: This image was extracted from a social media post. Analyze the actual visual content.')
            analysisType = 'image'
            sourceDetail = 'social media image'
          }
        }
      }
    }

    // ─── Strategy 4: Video platforms — fetch thumbnail and analyze ───
    if (!responseText && (contentType === 'youtube' || contentType === 'tiktok' || contentType === 'vimeo')) {
      console.log(`[Veritas AI] Video platform (${contentType}) — fetching thumbnail for analysis...`)

      const thumbnailUrls = getVideoThumbnailURL(url)
      let thumbnailFetched = false

      if (thumbnailUrls) {
        for (const thumbUrl of thumbnailUrls) {
          const imageData = await fetchImageFromURL(thumbUrl)
          if (imageData && imageData.size > 1000) {
            const videoThumbPrompt = `You are an expert deepfake forensics analyst. You are being shown a thumbnail/frame from a video. Analyze whether the visual content appears to be:
- Authentic/genuine footage
- AI-generated or deepfake content (face-swap, AI-generated person, etc.)
- Digitally manipulated

IMPORTANT: Do NOT flag real footage as deepfake just because faces look smooth or polished. Makeup, HD cameras, good lighting, and video compression all make real skin look smoother. Celebrities and public figures naturally look polished.

Only flag as deepfake if you see ACTUAL technical artifacts:
- Visible face-body boundary blending issues (halo effect, color mismatch at edges)
- Face that looks "pasted on" (different quality/sharpness than body/background)
- Blurry or distorted ears while the face is sharp
- Background warping near face edges
- An entirely synthetic-looking scene with no real-world camera artifacts

Signs of REAL footage: complex real-world environment, natural camera motion, real lighting, multiple people interacting naturally, genuine camera artifacts (blur, noise, lens effects).

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": <number 0-100>,
  "humanProbability": <number 0-100>,
  "confidence": <number 0-100>,
  "summary": "<2-3 sentence summary — mention this is based on a video thumbnail>",
  "patterns": [
    {"type": "warning|success|info", "text": "<observation>"}
  ],
  "explanation": "<detailed 3-4 sentence explanation. Be clear this analysis is based on a video thumbnail/preview frame and full video analysis would require the actual video file.>",
  "metrics": {
    "facialConsistency": "<natural|suspicious|anomalous|not_applicable>",
    "visualAuthenticity": "<authentic|synthetic|uncertain>",
    "analysisMethod": "thumbnail"
  }
}`
            responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType, videoThumbPrompt)
            analysisType = 'video'
            sourceDetail = `${contentType} video (thumbnail analysis)`
            thumbnailFetched = true
            break
          }
        }
      }

      // For TikTok or if thumbnail failed, try platform APIs then og:image
      if (!thumbnailFetched) {
        const platformImageUrl = await fetchImageFromPlatform(url)
        if (platformImageUrl) {
          const imageData = await fetchImageFromURL(platformImageUrl)
          if (imageData) {
            responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType,
              `Analyze this video thumbnail for AI-generated content indicators. This is a preview from a ${contentType} video. Focus on visual authenticity.\n\n` + IMAGE_ANALYSIS_PROMPT)
            analysisType = 'video'
            sourceDetail = `${contentType} video (preview analysis)`
            thumbnailFetched = true
          }
        }
      }

      if (!thumbnailFetched) {
        const ogImage = await extractOGImage(url)
        if (ogImage) {
          const imageData = await fetchImageFromURL(ogImage)
          if (imageData) {
            responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType,
              `Analyze this video thumbnail for AI-generated content indicators. This is a preview from a ${contentType} video. Focus on visual authenticity.\n\n` + IMAGE_ANALYSIS_PROMPT)
            analysisType = 'video'
            sourceDetail = `${contentType} video (preview analysis)`
          }
        }
      }
    }

    // ─── Strategy 5: Webpage — try fetching page text content or og:image ───
    if (!responseText && contentType === 'webpage') {
      console.log('[Veritas AI] Webpage URL — attempting to extract content...')

      // Try og:image first for visual analysis
      const ogImage = await extractOGImage(url)
      if (ogImage) {
        const imageData = await fetchImageFromURL(ogImage)
        if (imageData && imageData.size > 2000) {
          responseText = await callGeminiImageBase64(imageData.base64, imageData.mimeType,
            IMAGE_ANALYSIS_PROMPT + '\n\nNote: This image was extracted from a webpage. Analyze the visual content for AI generation indicators.')
          analysisType = 'image'
          sourceDetail = 'webpage image'
        }
      }

      // If no image, try to fetch page text
      if (!responseText) {
        const pageText = await fetchPageText(url)
        if (pageText && pageText.length > 50) {
          responseText = await callGeminiText(pageText.slice(0, 5000), TEXT_ANALYSIS_PROMPT)
          analysisType = 'text'
          sourceDetail = 'webpage text'
        }
      }
    }

    // ─── Fallback: URL-only analysis (last resort) ───
    if (!responseText) {
      console.log('[Veritas AI] Could not fetch content — falling back to URL-based analysis')
      const urlPrompt = `You are an AI content detection system. I'm giving you a URL that I could not fetch the actual content from (possibly due to CORS restrictions or authentication).

URL: ${url}
Detected content type: ${contentType}

Since you cannot see the actual content, be HONEST about your limitations. Do NOT make confident claims about the content.

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": 50,
  "humanProbability": 50,
  "confidence": <number 15-30>,
  "summary": "<explain that you could not access the actual content and therefore cannot make a reliable determination>",
  "patterns": [
    {"type": "info", "text": "Could not fetch actual content from URL — analysis is limited"},
    {"type": "info", "text": "<any observation based on URL structure>"}
  ],
  "explanation": "<explain that for accurate analysis, the user should download the image/video and upload it directly using the Image or Video tab instead>"
}

Be transparent. Do not pretend to have analyzed content you haven't seen.`

      responseText = await callGeminiText(url, urlPrompt)
      sourceDetail = 'URL-only (content not accessible)'
    }

    if (!responseText) return null

    const cleaned = responseText.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim()
    const analysis = JSON.parse(cleaned)

    return {
      type: analysisType,
      aiProbability: clamp(analysis.aiProbability, 0, 100),
      humanProbability: clamp(analysis.humanProbability, 0, 100),
      confidence: clamp(analysis.confidence, 0, 100),
      summary: analysis.summary,
      patterns: (analysis.patterns || []).map(p => ({
        type: p.type || 'info',
        text: p.text
      })),
      explanation: analysis.explanation,
      metrics: {
        url,
        sourceType: sourceDetail,
        ...(analysis.metrics || {})
      },
      chartData: generateChartData(analysis.aiProbability),
      poweredBy: analysisType === 'image' ? 'Gemini AI Vision' : analysisType === 'video' ? 'Gemini AI Vision' : 'Gemini AI'
    }
  } catch (error) {
    console.error('Gemini URL analysis error:', error?.message || error)
    return null
  }
}

/**
 * Extract og:image from a webpage via CORS proxy
 */
async function extractOGImage(url) {
  try {
    const proxies = [
      `https://corsproxy.io/?${encodeURIComponent(url)}`,
      `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
    ]

    for (const proxyUrl of proxies) {
      try {
        const response = await fetch(proxyUrl, {
          headers: { 'Accept': 'text/html,*/*' },
          signal: AbortSignal.timeout(8000)
        })

        if (!response.ok) continue

        const html = await response.text()
        if (!html || html.length < 100) continue

        // Extract og:image
        const ogMatch = html.match(/<meta[^>]*property=["']og:image["'][^>]*content=["']([^"']+)["']/i) ||
                         html.match(/<meta[^>]*content=["']([^"']+)["'][^>]*property=["']og:image["']/i)

        if (ogMatch && ogMatch[1]) {
          let ogImageUrl = ogMatch[1]
          // Handle relative URLs
          if (ogImageUrl.startsWith('/')) {
            const urlObj = new URL(url)
            ogImageUrl = `${urlObj.protocol}//${urlObj.host}${ogImageUrl}`
          }
          console.log(`[Veritas AI] ✓ Extracted og:image: ${ogImageUrl.slice(0, 100)}...`)
          return ogImageUrl
        }

        // Try twitter:image as fallback
        const twitterMatch = html.match(/<meta[^>]*(?:name|property)=["']twitter:image(?::src)?["'][^>]*content=["']([^"']+)["']/i)
        if (twitterMatch && twitterMatch[1]) {
          console.log(`[Veritas AI] ✓ Extracted twitter:image: ${twitterMatch[1].slice(0, 100)}...`)
          return twitterMatch[1]
        }
      } catch (e) {
        continue
      }
    }

    return null
  } catch (err) {
    console.warn('[Veritas AI] Failed to extract og:image:', err.message)
    return null
  }
}

/**
 * Try to fetch text content from a webpage
 */
async function fetchPageText(url) {
  try {
    const proxies = [
      `https://corsproxy.io/?${encodeURIComponent(url)}`,
      `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
    ]

    for (const proxyUrl of proxies) {
      try {
        const response = await fetch(proxyUrl, {
          headers: { 'Accept': 'text/html,*/*' },
          signal: AbortSignal.timeout(8000)
        })

        if (!response.ok) continue

        const html = await response.text()
        if (!html) continue

        // Strip HTML tags and extract text
        const div = document.createElement('div')
        div.innerHTML = html

        // Remove scripts, styles, nav, footer
        div.querySelectorAll('script, style, nav, footer, header, aside, noscript').forEach(el => el.remove())

        // Get text from article, main, or body
        const article = div.querySelector('article') || div.querySelector('main') || div.querySelector('.content') || div
        const text = article.textContent?.replace(/\s+/g, ' ').trim()

        if (text && text.length > 50) {
          console.log(`[Veritas AI] ✓ Extracted ${text.length} chars of page text`)
          return text
        }
      } catch (e) {
        continue
      }
    }

    return null
  } catch (err) {
    console.warn('[Veritas AI] Failed to fetch page text:', err.message)
    return null
  }
}

// ============================================================
// FALLBACK SIMULATION (when Gemini API key is not set)
// ============================================================

function simulateTextAnalysis(text) {
  const wordCount = text.split(/\s+/).filter(Boolean).length
  const sentenceCount = text.split(/[.!?]+/).filter(Boolean).length
  const avgWordLength = text.replace(/\s/g, '').length / Math.max(wordCount, 1)
  const uniqueWords = new Set(text.toLowerCase().split(/\s+/)).size
  const lexicalDiversity = uniqueWords / Math.max(wordCount, 1)

  const hasRepetitivePatterns = lexicalDiversity < 0.5
  const isVeryUniform = avgWordLength > 5.5 || avgWordLength < 3.5
  const hasLongSentences = wordCount / Math.max(sentenceCount, 1) > 25

  let aiProbability = 35 + Math.random() * 30
  if (hasRepetitivePatterns) aiProbability += 15
  if (isVeryUniform) aiProbability += 10
  if (hasLongSentences) aiProbability += 8
  if (wordCount < 20) aiProbability -= 15
  if (wordCount > 500) aiProbability += 5
  aiProbability = clamp(aiProbability, 12, 95)

  const patterns = []
  if (hasRepetitivePatterns) patterns.push({ type: 'warning', text: 'Low lexical diversity detected — common in AI-generated text' })
  if (isVeryUniform) patterns.push({ type: 'warning', text: 'Unusually uniform word length distribution' })
  if (hasLongSentences) patterns.push({ type: 'info', text: 'Extended sentence structures detected' })
  if (lexicalDiversity > 0.7) patterns.push({ type: 'success', text: 'High lexical diversity — typical of human writing' })
  if (wordCount > 100) patterns.push({ type: 'info', text: `Analyzed ${wordCount} words across ${sentenceCount} sentences` })

  const confidence = 60 + Math.random() * 30

  return {
    type: 'text',
    aiProbability: round1(aiProbability),
    humanProbability: round1(100 - aiProbability),
    confidence: round1(confidence),
    summary: aiProbability > 60
      ? 'This content shows significant indicators of AI generation. The writing patterns, vocabulary distribution, and structural consistency suggest machine-generated text.'
      : aiProbability > 40
        ? 'This content shows mixed indicators. Some patterns suggest AI involvement while others are consistent with human authorship.'
        : 'This content appears predominantly human-written. The writing style shows natural variation and authentic linguistic patterns.',
    patterns,
    metrics: { wordCount, sentenceCount, avgWordLength: round1(avgWordLength), lexicalDiversity: Math.round(lexicalDiversity * 100) / 100, uniqueWords },
    explanation: generateExplanation('text', aiProbability),
    chartData: generateChartData(aiProbability),
    poweredBy: 'Heuristic Analysis (add Gemini API key for AI-powered results)'
  }
}

function simulateImageAnalysis(fileName) {
  const aiProbability = 25 + Math.random() * 55
  const confidence = 55 + Math.random() * 35

  return {
    type: 'image',
    aiProbability: round1(aiProbability),
    humanProbability: round1(100 - aiProbability),
    confidence: round1(confidence),
    summary: aiProbability > 55
      ? 'This image shows indicators of AI generation or manipulation. Synthetic artifacts and unusual pixel patterns were detected during analysis.'
      : 'This image appears authentic. No significant AI generation markers or manipulation artifacts were detected.',
    patterns: [
      { type: aiProbability > 50 ? 'warning' : 'success', text: aiProbability > 50 ? 'Potential synthetic generation artifacts detected' : 'Image appears to be authentic' },
      { type: 'info', text: 'Metadata analysis complete' },
      { type: 'info', text: `File analyzed: ${fileName || 'uploaded image'}` }
    ],
    metrics: { resolution: 'N/A', format: fileName?.split('.').pop()?.toUpperCase() || 'JPEG', colorConsistency: round1(70 + Math.random() * 25) },
    explanation: generateExplanation('image', aiProbability),
    chartData: generateChartData(aiProbability),
    poweredBy: 'Heuristic Analysis (add Gemini API key for AI-powered results)'
  }
}

function simulateVideoAnalysis(fileName) {
  const aiProbability = 20 + Math.random() * 60
  const confidence = 50 + Math.random() * 35

  return {
    type: 'video',
    aiProbability: round1(aiProbability),
    humanProbability: round1(100 - aiProbability),
    confidence: round1(confidence),
    summary: aiProbability > 50
      ? 'This video shows potential deepfake characteristics. Suspicious artifacts were detected in facial regions and temporal consistency analysis.'
      : 'This video appears to be authentic. No significant deepfake indicators or manipulation artifacts were detected.',
    patterns: [
      { type: aiProbability > 50 ? 'warning' : 'success', text: aiProbability > 50 ? 'Potential deepfake indicators found' : 'Facial analysis appears consistent' },
      { type: 'info', text: 'Frame analysis complete' },
      { type: 'info', text: `File analyzed: ${fileName || 'uploaded video'}` }
    ],
    metrics: { framesAnalyzed: Math.floor(30 + Math.random() * 120), format: fileName?.split('.').pop()?.toUpperCase() || 'MP4', faceDetected: true },
    explanation: generateExplanation('video', aiProbability),
    chartData: generateChartData(aiProbability),
    poweredBy: 'Heuristic Analysis (add Gemini API key for AI-powered results)'
  }
}

function simulateURLAnalysis(url) {
  const aiProbability = 30 + Math.random() * 45
  const confidence = 55 + Math.random() * 30

  return {
    type: 'url',
    aiProbability: round1(aiProbability),
    humanProbability: round1(100 - aiProbability),
    confidence: round1(confidence),
    summary: aiProbability > 50
      ? 'The content from this URL shows indicators of AI generation.'
      : 'The content from this URL appears to be human-authored.',
    patterns: [
      { type: aiProbability > 50 ? 'warning' : 'success', text: aiProbability > 50 ? 'Content patterns suggest AI generation' : 'Content appears human-authored' },
      { type: 'info', text: `Source analyzed: ${url}` }
    ],
    metrics: { url, sourceType: 'article' },
    explanation: generateExplanation('url', aiProbability),
    chartData: generateChartData(aiProbability),
    poweredBy: 'Heuristic Analysis (add Gemini API key for AI-powered results)'
  }
}

// ============================================================
// UTILITY FUNCTIONS
// ============================================================

function clamp(val, min, max) {
  return Math.min(max, Math.max(min, Number(val) || 0))
}

function round1(val) {
  return Math.round(val * 10) / 10
}

function generateExplanation(type, probability) {
  const labels = { text: 'text content', image: 'image', video: 'video', url: 'web content' }
  const label = labels[type]

  if (probability > 70) {
    return `Our analysis engine detected strong indicators of AI generation in this ${label}. Multiple detection signals flagged synthetic patterns, unusual consistency, and markers typically associated with machine-generated content. While no detection system is 100% accurate, the confidence level suggests this content was likely created or significantly modified by AI.`
  } else if (probability > 45) {
    return `The analysis of this ${label} produced mixed results. Some indicators point toward AI involvement, while others suggest human authorship. This could indicate human-written content edited by AI, AI-generated content with human modifications, or naturally occurring patterns that coincidentally match AI markers.`
  } else {
    return `This ${label} shows predominantly human-authored characteristics. The natural variation in style, authentic patterns, and organic structure are consistent with human creation. Our detection algorithms found minimal indicators of AI generation.`
  }
}

function generateChartData(aiProbability) {
  const ai = Number(aiProbability) || 50
  return [
    { name: 'AI Patterns', score: Math.round(ai), fullMark: 100 },
    { name: 'Consistency', score: Math.round(clamp(40 + Math.random() * 50, 0, 100)), fullMark: 100 },
    { name: 'Complexity', score: Math.round(clamp(30 + Math.random() * 60, 0, 100)), fullMark: 100 },
    { name: 'Variation', score: Math.round(clamp(100 - ai + Math.random() * 20 - 10, 0, 100)), fullMark: 100 },
    { name: 'Authenticity', score: Math.round(100 - ai), fullMark: 100 },
    { name: 'Natural Flow', score: Math.round(clamp(100 - ai + Math.random() * 15, 0, 100)), fullMark: 100 }
  ]
}

// ============================================================
// MAIN EXPORT: analyzeContent
// ============================================================

/**
 * Main analysis function
 * @param {string} type - 'text' | 'image' | 'video' | 'url'
 * @param {string|File} data - The content to analyze (text string, File object, or URL string)
 * @param {function} onProgress - Progress callback
 */
export async function analyzeContent(type, data, onProgress) {
  const messages = SCAN_MESSAGES[type] || SCAN_MESSAGES.text
  const useGemini = isGeminiConfigured()

  // Show scanning animation
  const totalSteps = messages.length
  const stepDuration = useGemini ? 200 : 400 // Faster if Gemini handles the heavy lifting

  // Run progress animation and AI analysis concurrently
  const progressPromise = (async () => {
    for (let i = 0; i < totalSteps; i++) {
      if (onProgress) {
        onProgress({
          step: i + 1,
          total: totalSteps,
          message: messages[i],
          progress: ((i + 1) / totalSteps) * 100
        })
      }
      await new Promise(resolve => setTimeout(resolve, stepDuration))
    }
  })()

  let result = null

  // Try Gemini AI first
  if (useGemini) {
    const analysisPromise = (async () => {
      switch (type) {
        case 'text':
          return await analyzeTextWithGemini(data)
        case 'image':
          return await analyzeImageWithGemini(data)
        case 'video':
          return await analyzeVideoWithGemini(data)
        case 'url':
          return await analyzeURLWithGemini(data)
        default:
          return await analyzeTextWithGemini(data)
      }
    })()

    // Wait for both progress animation and analysis to complete
    const [_, geminiResult] = await Promise.all([progressPromise, analysisPromise])
    result = geminiResult
  } else {
    // Wait for progress animation to finish first
    await progressPromise
  }

  // Fallback to simulation if Gemini failed or wasn't configured
  if (!result) {
    switch (type) {
      case 'text':
        result = simulateTextAnalysis(data)
        break
      case 'image':
        result = simulateImageAnalysis(typeof data === 'object' ? data.name : data)
        break
      case 'video':
        result = simulateVideoAnalysis(typeof data === 'object' ? data.name : data)
        break
      case 'url':
        result = simulateURLAnalysis(data)
        break
      default:
        result = simulateTextAnalysis(data)
    }
  }

  return result
}

export { SCAN_MESSAGES }
