/**
 * AI Content Analysis Engine
 * Uses Google Gemini AI (free tier) for real analysis
 * Falls back to heuristic simulation when API key is not configured
 */

import { isGeminiConfigured, analyzeTextWithGemini as callGeminiText, analyzeImageWithGemini as callGeminiImage, analyzeVideoWithGemini as callGeminiVideo } from '../config/gemini'

// ============================================================
// SCAN STATUS MESSAGES
// ============================================================

const SCAN_MESSAGES = {
  text: [
    'Analyzing linguistic patterns…',
    'Checking syntactic consistency…',
    'Evaluating vocabulary distribution…',
    'Detecting repetitive phrasing…',
    'Scanning for AI writing markers…',
    'Analyzing sentence structure…',
    'Computing perplexity scores…',
    'Generating analysis report…'
  ],
  image: [
    'Analyzing pixel patterns…',
    'Checking for synthetic artifacts…',
    'Scanning metadata signatures…',
    'Evaluating color consistency…',
    'Detecting manipulation indicators…',
    'Analyzing noise patterns…',
    'Computing authenticity score…',
    'Generating analysis report…'
  ],
  video: [
    'Extracting key frames…',
    'Analyzing facial landmarks…',
    'Checking temporal consistency…',
    'Scanning for deepfake artifacts…',
    'Evaluating motion patterns…',
    'Analyzing audio-visual sync…',
    'Computing deepfake probability…',
    'Generating analysis report…'
  ],
  url: [
    'Fetching content from URL…',
    'Analyzing page structure…',
    'Extracting main content…',
    'Checking source credibility…',
    'Analyzing content patterns…',
    'Detecting synthetic generation…',
    'Computing analysis scores…',
    'Generating analysis report…'
  ]
}

// ============================================================
// GEMINI AI PROMPTS
// ============================================================

const TEXT_ANALYSIS_PROMPT = `You are an expert AI content detection system. Analyze the following text and determine whether it was written by a human or generated by AI (like ChatGPT, Claude, Gemini, etc.).

Evaluate these factors:
- Writing style consistency and naturalness
- Vocabulary diversity and word choice patterns
- Sentence structure variation
- Repetitive phrasing or formulaic patterns
- Burstiness (variation in sentence length/complexity — humans are more bursty)
- Perplexity (predictability of word choices — AI tends to be more predictable)
- Use of hedging language, filler phrases, or overly polished transitions
- Emotional authenticity and personal voice

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": <number 0-100>,
  "humanProbability": <number 0-100>,
  "confidence": <number 0-100>,
  "summary": "<2-3 sentence summary of findings>",
  "patterns": [
    {"type": "warning|success|info", "text": "<pattern description>"}
  ],
  "explanation": "<detailed 3-4 sentence explanation of why you reached this conclusion>",
  "metrics": {
    "writingStyle": "<natural|formulaic|mixed>",
    "burstiness": "<low|medium|high>",
    "predictability": "<low|medium|high>",
    "emotionalDepth": "<shallow|moderate|deep>"
  }
}

Text to analyze:
"""
{TEXT}
"""`

const IMAGE_ANALYSIS_PROMPT = `You are an expert AI image forensics analyst. Examine this image carefully and determine whether it is:
- A genuine photograph/human-created artwork
- Generated by AI (Midjourney, DALL-E, Stable Diffusion, etc.)
- Manipulated or doctored

Look for these indicators:
- Unnatural textures, skin smoothness, or hair patterns
- Inconsistent lighting, shadows, or reflections
- Distorted hands, fingers, teeth, or small details
- Text/letters that appear garbled or nonsensical
- Overly perfect symmetry or composition
- Unusual blending or artifact patterns around edges
- Background inconsistencies or repeating patterns
- Watermark artifacts from AI generators

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": <number 0-100>,
  "humanProbability": <number 0-100>,
  "confidence": <number 0-100>,
  "summary": "<2-3 sentence summary of findings>",
  "patterns": [
    {"type": "warning|success|info", "text": "<observation>"}
  ],
  "explanation": "<detailed 3-4 sentence explanation>",
  "metrics": {
    "textureConsistency": "<normal|suspicious|anomalous>",
    "lightingAnalysis": "<consistent|inconsistent>",
    "detailAccuracy": "<accurate|distorted|mixed>",
    "overallAuthenticity": "<authentic|synthetic|uncertain>"
  }
}`

const VIDEO_ANALYSIS_PROMPT = `You are an expert deepfake and AI video detection analyst. Based on what you can observe, analyze whether this video content appears to be:
- Authentic/original footage
- A deepfake or face-swap
- AI-generated video
- Manipulated or edited deceptively

Consider these factors:
- Facial feature consistency across expressions
- Lip sync accuracy
- Eye movement naturalness
- Skin texture and edge blending around faces
- Lighting consistency on the face vs. environment
- Head movement fluidity
- Background stability and consistency
- Audio-visual synchronization (if applicable)

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": <number 0-100>,
  "humanProbability": <number 0-100>,
  "confidence": <number 0-100>,
  "summary": "<2-3 sentence summary of findings>",
  "patterns": [
    {"type": "warning|success|info", "text": "<observation>"}
  ],
  "explanation": "<detailed 3-4 sentence explanation>",
  "metrics": {
    "facialConsistency": "<natural|suspicious|anomalous>",
    "temporalCoherence": "<stable|unstable|mixed>",
    "lipSyncAccuracy": "<accurate|inaccurate|not_applicable>",
    "overallAuthenticity": "<authentic|deepfake|uncertain>"
  }
}`

// ============================================================
// GEMINI-POWERED ANALYSIS FUNCTIONS
// ============================================================

async function analyzeTextWithGemini(text) {
  if (!isGeminiConfigured()) return null

  try {
    const responseText = await callGeminiText(text, TEXT_ANALYSIS_PROMPT)
    if (!responseText) return null

    // Clean response — remove markdown code fences if present
    const cleaned = responseText.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim()
    const analysis = JSON.parse(cleaned)

    // Compute text metrics locally
    const wordCount = text.split(/\s+/).filter(Boolean).length
    const sentenceCount = text.split(/[.!?]+/).filter(Boolean).length
    const uniqueWords = new Set(text.toLowerCase().split(/\s+/)).size
    const avgWordLength = text.replace(/\s/g, '').length / Math.max(wordCount, 1)
    const lexicalDiversity = uniqueWords / Math.max(wordCount, 1)

    return {
      type: 'text',
      aiProbability: clamp(analysis.aiProbability, 0, 100),
      humanProbability: clamp(analysis.humanProbability, 0, 100),
      confidence: clamp(analysis.confidence, 0, 100),
      summary: analysis.summary,
      patterns: (analysis.patterns || []).map(p => ({
        type: p.type || 'info',
        text: p.text
      })),
      explanation: analysis.explanation,
      metrics: {
        wordCount,
        sentenceCount,
        avgWordLength: Math.round(avgWordLength * 10) / 10,
        lexicalDiversity: Math.round(lexicalDiversity * 100) / 100,
        uniqueWords,
        ...(analysis.metrics || {})
      },
      chartData: generateChartData(analysis.aiProbability),
      poweredBy: 'Gemini AI'
    }
  } catch (error) {
    console.error('Gemini text analysis error:', error?.message || error)
    return null // Fallback to simulation
  }
}

async function analyzeImageWithGemini(imageFile) {
  if (!isGeminiConfigured() || !imageFile) return null

  try {
    const responseText = await callGeminiImage(imageFile, IMAGE_ANALYSIS_PROMPT)
    if (!responseText) return null

    const cleaned = responseText.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim()
    const analysis = JSON.parse(cleaned)

    return {
      type: 'image',
      aiProbability: clamp(analysis.aiProbability, 0, 100),
      humanProbability: clamp(analysis.humanProbability, 0, 100),
      confidence: clamp(analysis.confidence, 0, 100),
      summary: analysis.summary,
      patterns: (analysis.patterns || []).map(p => ({
        type: p.type || 'info',
        text: p.text
      })),
      explanation: analysis.explanation,
      metrics: {
        fileName: imageFile.name,
        fileSize: `${(imageFile.size / 1024).toFixed(1)} KB`,
        format: imageFile.type?.split('/')[1]?.toUpperCase() || 'UNKNOWN',
        ...(analysis.metrics || {})
      },
      chartData: generateChartData(analysis.aiProbability),
      poweredBy: 'Gemini AI Vision'
    }
  } catch (error) {
    console.error('Gemini image analysis error:', error?.message || error)
    return null
  }
}

async function analyzeVideoWithGemini(videoFile) {
  if (!isGeminiConfigured() || !videoFile) return null

  try {
    const responseText = await callGeminiVideo(videoFile, VIDEO_ANALYSIS_PROMPT)
    if (!responseText) return null

    const cleaned = responseText.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim()
    const analysis = JSON.parse(cleaned)

    return {
      type: 'video',
      aiProbability: clamp(analysis.aiProbability, 0, 100),
      humanProbability: clamp(analysis.humanProbability, 0, 100),
      confidence: clamp(analysis.confidence, 0, 100),
      summary: analysis.summary,
      patterns: (analysis.patterns || []).map(p => ({
        type: p.type || 'info',
        text: p.text
      })),
      explanation: analysis.explanation,
      metrics: {
        fileName: videoFile.name,
        fileSize: `${(videoFile.size / (1024 * 1024)).toFixed(1)} MB`,
        format: videoFile.type?.split('/')[1]?.toUpperCase() || 'MP4',
        ...(analysis.metrics || {})
      },
      chartData: generateChartData(analysis.aiProbability),
      poweredBy: 'Gemini AI Vision'
    }
  } catch (error) {
    console.error('Gemini video analysis error:', error)
    return null
  }
}

async function analyzeURLWithGemini(url) {
  if (!isGeminiConfigured()) return null

  try {
    // Check if URL points to an image
    const isImageUrl = /\.(jpg|jpeg|png|gif|webp|bmp|svg)/i.test(url) ||
      url.includes('/image') || url.includes('img') || url.includes('photo') ||
      url.includes('th.bing.com') || url.includes('googleusercontent.com') ||
      url.includes('images.unsplash.com') || url.includes('w=') || url.includes('h=');

    let responseText = null

    if (isImageUrl) {
      // For image URLs, try to fetch the image and analyze with vision
      try {
        const imgResponse = await fetch(url)
        const blob = await imgResponse.blob()
        const file = new File([blob], 'url-image.jpg', { type: blob.type || 'image/jpeg' })
        responseText = await callGeminiImage(file, IMAGE_ANALYSIS_PROMPT)
      } catch (fetchErr) {
        console.warn('Could not fetch image URL, falling back to text analysis:', fetchErr.message)
      }
    }

    // If image fetch failed or it's not an image URL, do text-based analysis
    if (!responseText) {
      const urlPrompt = `You are an AI content detection system. I'm giving you a URL. Based on common patterns for this type of URL and domain, analyze whether content from this source is likely AI-generated or human-created.

URL: ${url}

Consider:
- The domain reputation and type
- Common content patterns from this type of source
- Whether URLs like this typically host AI-generated content
- If this is an image or video URL (e.g., YouTube, TikTok, Instagram), do not attempt to watch/view the media. Instead, analyze the likelihood of the content being AI-generated based strictly on the source, domain reputation, and URL structure.

Return your analysis as valid JSON (no markdown, no code fences) with exactly this structure:
{
  "aiProbability": <number 0-100>,
  "humanProbability": <number 0-100>,
  "confidence": <number 0-100>,
  "summary": "<2-3 sentence summary>",
  "patterns": [
    {"type": "warning|success|info", "text": "<observation>"}
  ],
  "explanation": "<detailed 3-4 sentence explanation>"
}

Note: Base your analysis on the URL structure, domain patterns, and general knowledge. Be transparent about limitations.

{TEXT}`

      responseText = await callGeminiText(url, urlPrompt)
    }

    if (!responseText) return null

    const cleaned = responseText.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim()
    const analysis = JSON.parse(cleaned)

    return {
      type: 'url',
      aiProbability: clamp(analysis.aiProbability, 0, 100),
      humanProbability: clamp(analysis.humanProbability, 0, 100),
      confidence: clamp(analysis.confidence, 0, 100),
      summary: analysis.summary,
      patterns: (analysis.patterns || []).map(p => ({
        type: p.type || 'info',
        text: p.text
      })),
      explanation: analysis.explanation,
      metrics: {
        url,
        sourceType: isImageUrl ? 'image-url' : 'web',
        ...(analysis.metrics || {})
      },
      chartData: generateChartData(analysis.aiProbability),
      poweredBy: 'Gemini AI'
    }
  } catch (error) {
    console.error('Gemini URL analysis error:', error?.message || error)
    return null
  }
}

// ============================================================
// FALLBACK SIMULATION (when Gemini API key is not set)
// ============================================================

function simulateTextAnalysis(text) {
  const wordCount = text.split(/\s+/).filter(Boolean).length
  const sentenceCount = text.split(/[.!?]+/).filter(Boolean).length
  const avgWordLength = text.replace(/\s/g, '').length / Math.max(wordCount, 1)
  const uniqueWords = new Set(text.toLowerCase().split(/\s+/)).size
  const lexicalDiversity = uniqueWords / Math.max(wordCount, 1)

  const hasRepetitivePatterns = lexicalDiversity < 0.5
  const isVeryUniform = avgWordLength > 5.5 || avgWordLength < 3.5
  const hasLongSentences = wordCount / Math.max(sentenceCount, 1) > 25

  let aiProbability = 35 + Math.random() * 30
  if (hasRepetitivePatterns) aiProbability += 15
  if (isVeryUniform) aiProbability += 10
  if (hasLongSentences) aiProbability += 8
  if (wordCount < 20) aiProbability -= 15
  if (wordCount > 500) aiProbability += 5
  aiProbability = clamp(aiProbability, 12, 95)

  const patterns = []
  if (hasRepetitivePatterns) patterns.push({ type: 'warning', text: 'Low lexical diversity detected — common in AI-generated text' })
  if (isVeryUniform) patterns.push({ type: 'warning', text: 'Unusually uniform word length distribution' })
  if (hasLongSentences) patterns.push({ type: 'info', text: 'Extended sentence structures detected' })
  if (lexicalDiversity > 0.7) patterns.push({ type: 'success', text: 'High lexical diversity — typical of human writing' })
  if (wordCount > 100) patterns.push({ type: 'info', text: `Analyzed ${wordCount} words across ${sentenceCount} sentences` })

  const confidence = 60 + Math.random() * 30

  return {
    type: 'text',
    aiProbability: round1(aiProbability),
    humanProbability: round1(100 - aiProbability),
    confidence: round1(confidence),
    summary: aiProbability > 60
      ? 'This content shows significant indicators of AI generation. The writing patterns, vocabulary distribution, and structural consistency suggest machine-generated text.'
      : aiProbability > 40
        ? 'This content shows mixed indicators. Some patterns suggest AI involvement while others are consistent with human authorship.'
        : 'This content appears predominantly human-written. The writing style shows natural variation and authentic linguistic patterns.',
    patterns,
    metrics: { wordCount, sentenceCount, avgWordLength: round1(avgWordLength), lexicalDiversity: Math.round(lexicalDiversity * 100) / 100, uniqueWords },
    explanation: generateExplanation('text', aiProbability),
    chartData: generateChartData(aiProbability),
    poweredBy: 'Heuristic Analysis (add Gemini API key for AI-powered results)'
  }
}

function simulateImageAnalysis(fileName) {
  const aiProbability = 25 + Math.random() * 55
  const confidence = 55 + Math.random() * 35

  return {
    type: 'image',
    aiProbability: round1(aiProbability),
    humanProbability: round1(100 - aiProbability),
    confidence: round1(confidence),
    summary: aiProbability > 55
      ? 'This image shows indicators of AI generation or manipulation. Synthetic artifacts and unusual pixel patterns were detected during analysis.'
      : 'This image appears authentic. No significant AI generation markers or manipulation artifacts were detected.',
    patterns: [
      { type: aiProbability > 50 ? 'warning' : 'success', text: aiProbability > 50 ? 'Potential synthetic generation artifacts detected' : 'Image appears to be authentic' },
      { type: 'info', text: 'Metadata analysis complete' },
      { type: 'info', text: `File analyzed: ${fileName || 'uploaded image'}` }
    ],
    metrics: { resolution: 'N/A', format: fileName?.split('.').pop()?.toUpperCase() || 'JPEG', colorConsistency: round1(70 + Math.random() * 25) },
    explanation: generateExplanation('image', aiProbability),
    chartData: generateChartData(aiProbability),
    poweredBy: 'Heuristic Analysis (add Gemini API key for AI-powered results)'
  }
}

function simulateVideoAnalysis(fileName) {
  const aiProbability = 20 + Math.random() * 60
  const confidence = 50 + Math.random() * 35

  return {
    type: 'video',
    aiProbability: round1(aiProbability),
    humanProbability: round1(100 - aiProbability),
    confidence: round1(confidence),
    summary: aiProbability > 50
      ? 'This video shows potential deepfake characteristics. Suspicious artifacts were detected in facial regions and temporal consistency analysis.'
      : 'This video appears to be authentic. No significant deepfake indicators or manipulation artifacts were detected.',
    patterns: [
      { type: aiProbability > 50 ? 'warning' : 'success', text: aiProbability > 50 ? 'Potential deepfake indicators found' : 'Facial analysis appears consistent' },
      { type: 'info', text: 'Frame analysis complete' },
      { type: 'info', text: `File analyzed: ${fileName || 'uploaded video'}` }
    ],
    metrics: { framesAnalyzed: Math.floor(30 + Math.random() * 120), format: fileName?.split('.').pop()?.toUpperCase() || 'MP4', faceDetected: true },
    explanation: generateExplanation('video', aiProbability),
    chartData: generateChartData(aiProbability),
    poweredBy: 'Heuristic Analysis (add Gemini API key for AI-powered results)'
  }
}

function simulateURLAnalysis(url) {
  const aiProbability = 30 + Math.random() * 45
  const confidence = 55 + Math.random() * 30

  return {
    type: 'url',
    aiProbability: round1(aiProbability),
    humanProbability: round1(100 - aiProbability),
    confidence: round1(confidence),
    summary: aiProbability > 50
      ? 'The content from this URL shows indicators of AI generation.'
      : 'The content from this URL appears to be human-authored.',
    patterns: [
      { type: aiProbability > 50 ? 'warning' : 'success', text: aiProbability > 50 ? 'Content patterns suggest AI generation' : 'Content appears human-authored' },
      { type: 'info', text: `Source analyzed: ${url}` }
    ],
    metrics: { url, sourceType: 'article' },
    explanation: generateExplanation('url', aiProbability),
    chartData: generateChartData(aiProbability),
    poweredBy: 'Heuristic Analysis (add Gemini API key for AI-powered results)'
  }
}

// ============================================================
// UTILITY FUNCTIONS
// ============================================================

function clamp(val, min, max) {
  return Math.min(max, Math.max(min, Number(val) || 0))
}

function round1(val) {
  return Math.round(val * 10) / 10
}

function generateExplanation(type, probability) {
  const labels = { text: 'text content', image: 'image', video: 'video', url: 'web content' }
  const label = labels[type]

  if (probability > 70) {
    return `Our analysis engine detected strong indicators of AI generation in this ${label}. Multiple detection signals flagged synthetic patterns, unusual consistency, and markers typically associated with machine-generated content. While no detection system is 100% accurate, the confidence level suggests this content was likely created or significantly modified by AI.`
  } else if (probability > 45) {
    return `The analysis of this ${label} produced mixed results. Some indicators point toward AI involvement, while others suggest human authorship. This could indicate human-written content edited by AI, AI-generated content with human modifications, or naturally occurring patterns that coincidentally match AI markers.`
  } else {
    return `This ${label} shows predominantly human-authored characteristics. The natural variation in style, authentic patterns, and organic structure are consistent with human creation. Our detection algorithms found minimal indicators of AI generation.`
  }
}

function generateChartData(aiProbability) {
  const ai = Number(aiProbability) || 50
  return [
    { name: 'AI Patterns', score: Math.round(ai), fullMark: 100 },
    { name: 'Consistency', score: Math.round(clamp(40 + Math.random() * 50, 0, 100)), fullMark: 100 },
    { name: 'Complexity', score: Math.round(clamp(30 + Math.random() * 60, 0, 100)), fullMark: 100 },
    { name: 'Variation', score: Math.round(clamp(100 - ai + Math.random() * 20 - 10, 0, 100)), fullMark: 100 },
    { name: 'Authenticity', score: Math.round(100 - ai), fullMark: 100 },
    { name: 'Natural Flow', score: Math.round(clamp(100 - ai + Math.random() * 15, 0, 100)), fullMark: 100 }
  ]
}

// ============================================================
// MAIN EXPORT: analyzeContent
// ============================================================

/**
 * Main analysis function
 * @param {string} type - 'text' | 'image' | 'video' | 'url'
 * @param {string|File} data - The content to analyze (text string, File object, or URL string)
 * @param {function} onProgress - Progress callback
 */
export async function analyzeContent(type, data, onProgress) {
  const messages = SCAN_MESSAGES[type] || SCAN_MESSAGES.text
  const useGemini = isGeminiConfigured()

  // Show scanning animation
  const totalSteps = messages.length
  const stepDuration = useGemini ? 200 : 400 // Faster if Gemini handles the heavy lifting

  // Run progress animation and AI analysis concurrently
  const progressPromise = (async () => {
    for (let i = 0; i < totalSteps; i++) {
      if (onProgress) {
        onProgress({
          step: i + 1,
          total: totalSteps,
          message: messages[i],
          progress: ((i + 1) / totalSteps) * 100
        })
      }
      await new Promise(resolve => setTimeout(resolve, stepDuration))
    }
  })()

  let result = null

  // Try Gemini AI first
  if (useGemini) {
    const analysisPromise = (async () => {
      switch (type) {
        case 'text':
          return await analyzeTextWithGemini(data)
        case 'image':
          return await analyzeImageWithGemini(data)
        case 'video':
          return await analyzeVideoWithGemini(data)
        case 'url':
          return await analyzeURLWithGemini(data)
        default:
          return await analyzeTextWithGemini(data)
      }
    })()

    // Wait for both progress animation and analysis to complete
    const [_, geminiResult] = await Promise.all([progressPromise, analysisPromise])
    result = geminiResult
  } else {
    // Wait for progress animation to finish first
    await progressPromise
  }

  // Fallback to simulation if Gemini failed or wasn't configured
  if (!result) {
    switch (type) {
      case 'text':
        result = simulateTextAnalysis(data)
        break
      case 'image':
        result = simulateImageAnalysis(typeof data === 'object' ? data.name : data)
        break
      case 'video':
        result = simulateVideoAnalysis(typeof data === 'object' ? data.name : data)
        break
      case 'url':
        result = simulateURLAnalysis(data)
        break
      default:
        result = simulateTextAnalysis(data)
    }
  }

  return result
}

export { SCAN_MESSAGES }
